package com.addoiles.entity;

public class OilArticle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_article.id
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_article.article_id
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private String article_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_article.user_id
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private String user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_article.title
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_article.content
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_article.type
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_article.delete_status
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private Integer delete_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_article.favourite
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private Integer favourite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_article.create_time
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private Integer create_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_article.id
     *
     * @return the value of oil_article.id
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_article.id
     *
     * @param id the value for oil_article.id
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_article.article_id
     *
     * @return the value of oil_article.article_id
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public String getArticle_id() {
        return article_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_article.article_id
     *
     * @param article_id the value for oil_article.article_id
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setArticle_id(String article_id) {
        this.article_id = article_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_article.user_id
     *
     * @return the value of oil_article.user_id
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public String getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_article.user_id
     *
     * @param user_id the value for oil_article.user_id
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_article.title
     *
     * @return the value of oil_article.title
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_article.title
     *
     * @param title the value for oil_article.title
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_article.content
     *
     * @return the value of oil_article.content
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_article.content
     *
     * @param content the value for oil_article.content
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_article.type
     *
     * @return the value of oil_article.type
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_article.type
     *
     * @param type the value for oil_article.type
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_article.delete_status
     *
     * @return the value of oil_article.delete_status
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public Integer getDelete_status() {
        return delete_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_article.delete_status
     *
     * @param delete_status the value for oil_article.delete_status
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setDelete_status(Integer delete_status) {
        this.delete_status = delete_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_article.favourite
     *
     * @return the value of oil_article.favourite
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public Integer getFavourite() {
        return favourite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_article.favourite
     *
     * @param favourite the value for oil_article.favourite
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setFavourite(Integer favourite) {
        this.favourite = favourite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_article.create_time
     *
     * @return the value of oil_article.create_time
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public Integer getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_article.create_time
     *
     * @param create_time the value for oil_article.create_time
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setCreate_time(Integer create_time) {
        this.create_time = create_time;
    }
}