package com.addoiles.entity;

public class OilShare {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_share.id
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_share.title
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_share.content
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_share.favorite
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private Integer favorite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_share.dislike
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private Integer dislike;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_share.delete_status
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private Integer delete_status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_share.id
     *
     * @return the value of oil_share.id
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_share.id
     *
     * @param id the value for oil_share.id
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_share.title
     *
     * @return the value of oil_share.title
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_share.title
     *
     * @param title the value for oil_share.title
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_share.content
     *
     * @return the value of oil_share.content
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_share.content
     *
     * @param content the value for oil_share.content
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_share.favorite
     *
     * @return the value of oil_share.favorite
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public Integer getFavorite() {
        return favorite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_share.favorite
     *
     * @param favorite the value for oil_share.favorite
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setFavorite(Integer favorite) {
        this.favorite = favorite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_share.dislike
     *
     * @return the value of oil_share.dislike
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public Integer getDislike() {
        return dislike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_share.dislike
     *
     * @param dislike the value for oil_share.dislike
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setDislike(Integer dislike) {
        this.dislike = dislike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_share.delete_status
     *
     * @return the value of oil_share.delete_status
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public Integer getDelete_status() {
        return delete_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_share.delete_status
     *
     * @param delete_status the value for oil_share.delete_status
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setDelete_status(Integer delete_status) {
        this.delete_status = delete_status;
    }
}