package com.addoiles.entity;

public class OilUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_user.id
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_user.user_id
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private String user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_user.user_name
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private String user_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_user.password
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_user.delete_status
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private Integer delete_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_user.email
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_user.create_time
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    private Integer create_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_user.id
     *
     * @return the value of oil_user.id
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_user.id
     *
     * @param id the value for oil_user.id
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_user.user_id
     *
     * @return the value of oil_user.user_id
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public String getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_user.user_id
     *
     * @param user_id the value for oil_user.user_id
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_user.user_name
     *
     * @return the value of oil_user.user_name
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public String getUser_name() {
        return user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_user.user_name
     *
     * @param user_name the value for oil_user.user_name
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_user.password
     *
     * @return the value of oil_user.password
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_user.password
     *
     * @param password the value for oil_user.password
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_user.delete_status
     *
     * @return the value of oil_user.delete_status
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public Integer getDelete_status() {
        return delete_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_user.delete_status
     *
     * @param delete_status the value for oil_user.delete_status
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setDelete_status(Integer delete_status) {
        this.delete_status = delete_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_user.email
     *
     * @return the value of oil_user.email
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_user.email
     *
     * @param email the value for oil_user.email
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_user.create_time
     *
     * @return the value of oil_user.create_time
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public Integer getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_user.create_time
     *
     * @param create_time the value for oil_user.create_time
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    public void setCreate_time(Integer create_time) {
        this.create_time = create_time;
    }
}