package com.addoiles.entity;

public class OilArticle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_article.id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_article.article_id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    private String articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_article.user_id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_article.title
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_article.content
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_article.type
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_article.delete_status
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    private Integer deleteStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_article.favourite
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    private Integer favourite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_article.create_time
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    private Integer createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_article.id
     *
     * @return the value of oil_article.id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_article.id
     *
     * @param id the value for oil_article.id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_article.article_id
     *
     * @return the value of oil_article.article_id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_article.article_id
     *
     * @param articleId the value for oil_article.article_id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_article.user_id
     *
     * @return the value of oil_article.user_id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_article.user_id
     *
     * @param userId the value for oil_article.user_id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_article.title
     *
     * @return the value of oil_article.title
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_article.title
     *
     * @param title the value for oil_article.title
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_article.content
     *
     * @return the value of oil_article.content
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_article.content
     *
     * @param content the value for oil_article.content
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_article.type
     *
     * @return the value of oil_article.type
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_article.type
     *
     * @param type the value for oil_article.type
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_article.delete_status
     *
     * @return the value of oil_article.delete_status
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_article.delete_status
     *
     * @param deleteStatus the value for oil_article.delete_status
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_article.favourite
     *
     * @return the value of oil_article.favourite
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public Integer getFavourite() {
        return favourite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_article.favourite
     *
     * @param favourite the value for oil_article.favourite
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public void setFavourite(Integer favourite) {
        this.favourite = favourite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_article.create_time
     *
     * @return the value of oil_article.create_time
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_article.create_time
     *
     * @param createTime the value for oil_article.create_time
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }
}