package com.addoiles.entity;

public class OilComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_comment.id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_comment.comment_id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    private String commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_comment.delete_status
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    private Integer deleteStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_comment.user_id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_comment.create_time
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    private Integer createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_comment.id
     *
     * @return the value of oil_comment.id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_comment.id
     *
     * @param id the value for oil_comment.id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_comment.comment_id
     *
     * @return the value of oil_comment.comment_id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public String getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_comment.comment_id
     *
     * @param commentId the value for oil_comment.comment_id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public void setCommentId(String commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_comment.delete_status
     *
     * @return the value of oil_comment.delete_status
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_comment.delete_status
     *
     * @param deleteStatus the value for oil_comment.delete_status
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_comment.user_id
     *
     * @return the value of oil_comment.user_id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_comment.user_id
     *
     * @param userId the value for oil_comment.user_id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_comment.create_time
     *
     * @return the value of oil_comment.create_time
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_comment.create_time
     *
     * @param createTime the value for oil_comment.create_time
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }
}