package com.addoiles.entity;

public class OilUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_user.id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_user.user_id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_user.user_name
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_user.password
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_user.delete_status
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    private Integer deleteStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_user.email
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oil_user.create_time
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    private Integer createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_user.id
     *
     * @return the value of oil_user.id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_user.id
     *
     * @param id the value for oil_user.id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_user.user_id
     *
     * @return the value of oil_user.user_id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_user.user_id
     *
     * @param userId the value for oil_user.user_id
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_user.user_name
     *
     * @return the value of oil_user.user_name
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_user.user_name
     *
     * @param userName the value for oil_user.user_name
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_user.password
     *
     * @return the value of oil_user.password
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_user.password
     *
     * @param password the value for oil_user.password
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_user.delete_status
     *
     * @return the value of oil_user.delete_status
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_user.delete_status
     *
     * @param deleteStatus the value for oil_user.delete_status
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_user.email
     *
     * @return the value of oil_user.email
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_user.email
     *
     * @param email the value for oil_user.email
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oil_user.create_time
     *
     * @return the value of oil_user.create_time
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oil_user.create_time
     *
     * @param createTime the value for oil_user.create_time
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }
}