package com.addoiles.dao;

import com.addoiles.entity.OilUser;

public interface OilUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_user
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_user
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    int insert(OilUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_user
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    int insertSelective(OilUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_user
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    OilUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_user
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    int updateByPrimaryKeySelective(OilUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_user
     *
     * @mbggenerated Tue Jul 18 00:32:24 CST 2017
     */
    int updateByPrimaryKey(OilUser record);
}