package com.addoiles.dao;

import com.addoiles.entity.OilArticle;

public interface OilArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_article
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_article
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    int insert(OilArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_article
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    int insertSelective(OilArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_article
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    OilArticle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_article
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    int updateByPrimaryKeySelective(OilArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_article
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    int updateByPrimaryKey(OilArticle record);
}