package com.addoiles.dao;

import com.addoiles.entity.OilComment;

public interface OilCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_comment
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_comment
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    int insert(OilComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_comment
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    int insertSelective(OilComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_comment
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    OilComment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_comment
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    int updateByPrimaryKeySelective(OilComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_comment
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    int updateByPrimaryKey(OilComment record);
}