package com.addoiles.dao;

import com.addoiles.entity.OilShare;

public interface OilShareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_share
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_share
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    int insert(OilShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_share
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    int insertSelective(OilShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_share
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    OilShare selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_share
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    int updateByPrimaryKeySelective(OilShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_share
     *
     * @mbggenerated Tue Jul 18 18:18:00 CST 2017
     */
    int updateByPrimaryKey(OilShare record);
}