package com.shamrock.cms.entity;

import java.util.Date;

public class Admin {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.adminId
	 * @mbggenerated  Mon Aug 29 21:59:00 CST 2016
	 */
	private Long adminId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.name
	 * @mbggenerated  Mon Aug 29 21:59:00 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.password
	 * @mbggenerated  Mon Aug 29 21:59:00 CST 2016
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.createTime
	 * @mbggenerated  Mon Aug 29 21:59:00 CST 2016
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.adminId
	 * @return  the value of admin.adminId
	 * @mbggenerated  Mon Aug 29 21:59:00 CST 2016
	 */
	public Long getAdminId() {
		return adminId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.adminId
	 * @param adminId  the value for admin.adminId
	 * @mbggenerated  Mon Aug 29 21:59:00 CST 2016
	 */
	public void setAdminId(Long adminId) {
		this.adminId = adminId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.name
	 * @return  the value of admin.name
	 * @mbggenerated  Mon Aug 29 21:59:00 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.name
	 * @param name  the value for admin.name
	 * @mbggenerated  Mon Aug 29 21:59:00 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.password
	 * @return  the value of admin.password
	 * @mbggenerated  Mon Aug 29 21:59:00 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.password
	 * @param password  the value for admin.password
	 * @mbggenerated  Mon Aug 29 21:59:00 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.createTime
	 * @return  the value of admin.createTime
	 * @mbggenerated  Mon Aug 29 21:59:00 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.createTime
	 * @param createTime  the value for admin.createTime
	 * @mbggenerated  Mon Aug 29 21:59:00 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}