package com.shamrock.cms.entity;

import java.util.Date;

public class AdminFolder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_folder.adminId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    private Long adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_folder.folderId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    private Long folderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_folder.createTime
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_folder.adminId
     *
     * @return the value of admin_folder.adminId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_folder.adminId
     *
     * @param adminId the value for admin_folder.adminId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_folder.folderId
     *
     * @return the value of admin_folder.folderId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public Long getFolderId() {
        return folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_folder.folderId
     *
     * @param folderId the value for admin_folder.folderId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setFolderId(Long folderId) {
        this.folderId = folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_folder.createTime
     *
     * @return the value of admin_folder.createTime
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_folder.createTime
     *
     * @param createTime the value for admin_folder.createTime
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}