package com.shamrock.cms.entity;

import java.util.Date;

import com.shamrock.cms.constant.CommentConstant;

public class Comment {
  
    private Long commentId;

   
    private Long userId;

    
    private Long fatherId;

   
    private Long kindId;

    
    private CommentConstant.Kind kind;

    private String name;

    
    private String email;

   
    private String url;

   
    private Long phone;

    
    private String ip;

    private CommentConstant.Status status;

    
    private Date createTime;

   
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentId
     *
     * @return the value of comment.commentId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentId
     *
     * @param commentId the value for comment.commentId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.userId
     *
     * @return the value of comment.userId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.userId
     *
     * @param userId the value for comment.userId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.fatherId
     *
     * @return the value of comment.fatherId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public Long getFatherId() {
        return fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.fatherId
     *
     * @param fatherId the value for comment.fatherId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setFatherId(Long fatherId) {
        this.fatherId = fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.kindId
     *
     * @return the value of comment.kindId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public Long getKindId() {
        return kindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.kindId
     *
     * @param kindId the value for comment.kindId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setKindId(Long kindId) {
        this.kindId = kindId;
    }

   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.name
     *
     * @return the value of comment.name
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.name
     *
     * @param name the value for comment.name
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.email
     *
     * @return the value of comment.email
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.email
     *
     * @param email the value for comment.email
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.url
     *
     * @return the value of comment.url
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.url
     *
     * @param url the value for comment.url
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.phone
     *
     * @return the value of comment.phone
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public Long getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.phone
     *
     * @param phone the value for comment.phone
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setPhone(Long phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.ip
     *
     * @return the value of comment.ip
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.ip
     *
     * @param ip the value for comment.ip
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

  

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.createTime
     *
     * @return the value of comment.createTime
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.createTime
     *
     * @param createTime the value for comment.createTime
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

	public CommentConstant.Kind getKind() {
		return kind;
	}

	public void setKind(CommentConstant.Kind kind) {
		this.kind = kind;
	}

	public CommentConstant.Status getStatus() {
		return status;
	}

	public void setStatus(CommentConstant.Status status) {
		this.status = status;
	}
    
    
}