package com.shamrock.cms.entity;

import java.util.Date;

import com.shamrock.cms.constant.GuestbookConstant;

public class Guestbook {
 
    private Long guestbookId;

  
    private String name;

  
    private String email;

   
    private String website;

   
    private String title;

 
    private String content;

 
    private String reply;

  
    private GuestbookConstant.Status status;

  
    private Date createTime;

    
    private Date replyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guestbook.guestbookId
     *
     * @return the value of guestbook.guestbookId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public Long getGuestbookId() {
        return guestbookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guestbook.guestbookId
     *
     * @param guestbookId the value for guestbook.guestbookId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setGuestbookId(Long guestbookId) {
        this.guestbookId = guestbookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guestbook.name
     *
     * @return the value of guestbook.name
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guestbook.name
     *
     * @param name the value for guestbook.name
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guestbook.email
     *
     * @return the value of guestbook.email
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guestbook.email
     *
     * @param email the value for guestbook.email
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guestbook.website
     *
     * @return the value of guestbook.website
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guestbook.website
     *
     * @param website the value for guestbook.website
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setWebsite(String website) {
        this.website = website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guestbook.title
     *
     * @return the value of guestbook.title
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guestbook.title
     *
     * @param title the value for guestbook.title
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guestbook.content
     *
     * @return the value of guestbook.content
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guestbook.content
     *
     * @param content the value for guestbook.content
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guestbook.reply
     *
     * @return the value of guestbook.reply
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guestbook.reply
     *
     * @param reply the value for guestbook.reply
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setReply(String reply) {
        this.reply = reply;
    }



    public GuestbookConstant.Status getStatus() {
		return status;
	}

	public void setStatus(GuestbookConstant.Status status) {
		this.status = status;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guestbook.createTime
     *
     * @return the value of guestbook.createTime
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guestbook.createTime
     *
     * @param createTime the value for guestbook.createTime
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guestbook.replyTime
     *
     * @return the value of guestbook.replyTime
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public Date getReplyTime() {
        return replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guestbook.replyTime
     *
     * @param replyTime the value for guestbook.replyTime
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setReplyTime(Date replyTime) {
        this.replyTime = replyTime;
    }
}