package com.shamrock.cms.entity;

import java.util.Date;

public class Headline {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headline.headlineId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    private Long headlineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headline.name
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headline.picture
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headline.url
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headline.sort
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    private int sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headline.createTime
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headline.headlineId
     *
     * @return the value of headline.headlineId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public Long getHeadlineId() {
        return headlineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headline.headlineId
     *
     * @param headlineId the value for headline.headlineId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setHeadlineId(Long headlineId) {
        this.headlineId = headlineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headline.name
     *
     * @return the value of headline.name
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headline.name
     *
     * @param name the value for headline.name
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headline.picture
     *
     * @return the value of headline.picture
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headline.picture
     *
     * @param picture the value for headline.picture
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headline.url
     *
     * @return the value of headline.url
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headline.url
     *
     * @param url the value for headline.url
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setUrl(String url) {
        this.url = url;
    }

    

    public int getSort() {
		return sort;
	}

	public void setSort(int sort) {
		this.sort = sort;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headline.createTime
     *
     * @return the value of headline.createTime
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headline.createTime
     *
     * @param createTime the value for headline.createTime
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}