package com.shamrock.cms.entity;

import java.util.Date;

import com.shamrock.cms.constant.MediaConstant;

public class Media {
 
    private Long mediaId;


    private Long kindId;


    private String name;

  
    private String path;


    private Long size;


    private MediaConstant.Type type;


    private MediaConstant.Kind kind;


    private Date createTime;


    public Long getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.mediaId
     *
     * @param mediaId the value for media.mediaId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setMediaId(Long mediaId) {
        this.mediaId = mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.kindId
     *
     * @return the value of media.kindId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public Long getKindId() {
        return kindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.kindId
     *
     * @param kindId the value for media.kindId
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setKindId(Long kindId) {
        this.kindId = kindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.name
     *
     * @return the value of media.name
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.name
     *
     * @param name the value for media.name
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.path
     *
     * @return the value of media.path
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.path
     *
     * @param path the value for media.path
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setPath(String path) {
        this.path = path;
    }


   

  

    public Long getSize() {
		return size;
	}

	public void setSize(Long size) {
		this.size = size;
	}

	public MediaConstant.Type getType() {
		return type;
	}

	public void setType(MediaConstant.Type type) {
		this.type = type;
	}

	public MediaConstant.Kind getKind() {
		return kind;
	}

	public void setKind(MediaConstant.Kind kind) {
		this.kind = kind;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column media.createTime
     *
     * @return the value of media.createTime
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column media.createTime
     *
     * @param createTime the value for media.createTime
     *
     * @mbggenerated Mon Aug 29 21:59:00 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}